# Generated by Django 5.2 on 2025-05-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='planexercise',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='planexercise',
            name='reps',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='frequency_per_week',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.exercisecategory'),
        ),
    ]
