# Generated by Django 5.2 on 2025-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercisecategory_remove_exercise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planexercise',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='planexercise',
            name='reps',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
