# Generated by Django 5.2 on 2025-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_planexercise_repetitions_planexercise_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planexercise',
            name='frequency_per_week',
            field=models.PositiveIntegerField(),
        ),
    ]
